Set-Location $PSScriptRoot
# Generated by PAC and GO Admin - 5/6/2026
# New Agent: Patty Wells

$name    = "Patty Wells"
$slug    = "patty-wells"
$email   = "pacandgopatty@gmail.com"
$tagline = "Co-Owner & Senior Travel Specialist"
$clia    = "456611"
$sot     = "40802"
$photo   = "agent-profile.jpg"

$src  = "$PSScriptRoot\agents\robert-traversi"
$dest = "$PSScriptRoot\agents\$slug"

if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
Write-Host "Copying template..." -ForegroundColor Cyan
Copy-Item $src $dest -Recurse

Write-Host "Replacing values..." -ForegroundColor Cyan
Get-ChildItem "$dest\*.html" | ForEach-Object {
    $c = Get-Content $_.FullName -Raw -Encoding UTF8
    $c = $c -replace "robert-traversi",                                 $slug
    $c = $c -replace "Robert Traversi",                                 $name
    $c = $c -replace "pacandgorob@gmail\.com",                         $email
    $c = $c -replace "Travel Specialist · Cruise Expert · Adventure Seeker", $tagline
    $c = $c -replace "robandkaty-profile\.jpg",                        $photo
    $c = $c -replace "CLIA #456611",                                    "CLIA #$clia"
    $c = $c -replace "Florida Seller of Travel #40802",                 "Florida Seller of Travel #$sot"
    Set-Content $_.FullName $c -Encoding UTF8 -NoNewline
}

$sc = Get-Content "$PSScriptRoot\agents\robert-traversi.html" -Raw -Encoding UTF8
$sc = $sc -replace "robert-traversi", $slug
$sc = $sc -replace "Robert Traversi",  $name
Set-Content "$PSScriptRoot\agents\$slug.html" $sc -Encoding UTF8 -NoNewline

Write-Host "" 
Write-Host "Done! agents\$slug\ is ready." -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Edit bio in agents\$slug\index.html (search bio-text)"
Write-Host "  2. Place photo at images\uploads\$photo"
Write-Host "  3. Run in Supabase SQL Editor:"
Write-Host "     INSERT INTO settings (agent_id) VALUES ('$slug');" -ForegroundColor White
Write-Host "  4. Run deploy.ps1 to publish"
Write-Host ""
